//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASGlobal.Employees.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MASGlobal.Employees.Shared.Resources.Rest", typeof(Rest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string ExternalAllEmployeesResource {
            get {
                return ResourceManager.GetString("ExternalAllEmployeesResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to masglobaltestapi.azurewebsites.net/api/.
        /// </summary>
        public static string ExternalEmployeeBaseUri {
            get {
                return ResourceManager.GetString("ExternalEmployeeBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees/all.
        /// </summary>
        public static string InternalAllEmployeesResource {
            get {
                return ResourceManager.GetString("InternalAllEmployeesResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost:44344/api/.
        /// </summary>
        public static string InternalEmployeeBaseUri {
            get {
                return ResourceManager.GetString("InternalEmployeeBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees/{employeeId}.
        /// </summary>
        public static string InternalSingleEmployeesResource {
            get {
                return ResourceManager.GetString("InternalSingleEmployeesResource", resourceCulture);
            }
        }
    }
}
